# Generated by Django 6.0.2 on 2026-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='VendorMetrics',
        ),
    ]
