# Generated by Django 6.0.2 on 2026-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vendor_delete_vendormetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMetrics',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'v_vendor_metrics',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
